require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/AbcSize:
  Exclude:
    - 'lib/**/*.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/**/*.rb'
Metrics/MethodLength:
  Exclude:
    - 'lib/**/*.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/**/*.rb'
Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 250
RSpec/Be:
  Exclude:
    - 'spec/**/*.rb'
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NotToNot:
  Exclude:
    - 'spec/**/*.rb'
